#!/usr/bin/perl -w

=head1 NAME

perlfinder - a GTK2/GLADE MacOS X Finder workalike

=head1 SYNOPSIS

 # Start perlfinder
 src/perlfinder

=head1 DESCRIPTION

PerlFinder is a simple program that I was developing to make a MacOS X
Finder workalike.

=head1 REQUIRES

PerlFinder currently requires the following:

    * Gtk2
    * Gtk2::GladeXML
    * XML::Simple

These can be fetched from your local CPAN mirror.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify
it under the terms  of the GNU General Public License as published
by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNEESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details. 

You should have recieved a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA.

=head1 BUGS

* If you have a $HOME/.perlfinder remove it first before
  running. There is a bug that prevents the program from running
  completely at this point in time.

=head1 AUTHOR

June R. Tate <june@theonelab.com>

=cut

use lib (-e '@LIBDIR@' ? '@LIBDIR@' : $ENV{PWD} .'/lib');
use PerlFinder::PerlFinder;
use Data::Dumper;

$pf = new PerlFinder::PerlFinder();
$pf->startPerlFinder();
